services:
    - docker

before_install:
    - docker build -t container-crawler test/container
    - container_id=$(mktemp)
    - docker run -d -v `pwd`:/container-crawler container-crawler > "${container_id}"

script:
    - docker exec -it `cat ${container_id}` /bin/bash -c 'cd /container-crawler; flake8'
    - docker exec -it `cat ${container_id}` /bin/bash -c 'cd /container-crawler; nosetests test/unit'
